### ISSUE TITLE
Tagging plan

### ISSUE THREAD

**Issue by wookay** [JuliaLang/ZMQ.jl#110]
thank you for inviting me as a collaborator.
I'd like to tag two versions.

- [x] ZMQ.jl v0.3.4
  - support Julia 0.3
  - REQUIRE
     - BinDeps 0.3.21 (to avoid the ```MethodError: `joinpath` has no method matching joinpath```)

- [ ] ZMQ.jl v0.4.0
  - drop support Julia 0.3
  - REQUIRE
     - BinDeps 0.3.22 (check absolute path of powershell, accept lowercase `sha =` arguments)

**Comment by tkelman** [comment]
Unless those minimum versions fix bugs that cause errors, they're likely too conservative.

**Comment by wookay** [comment]
changed versions. thanks.

ZMQ.jl v0.3.4
- REQUIRE: BinDeps 0.3.22

ZMQ.jl v.0.3.5
- REQUIRE: BinDeps 0.4.1

**Comment by tkelman** [comment]
BinDeps dropping 0.3 support isn't relevant for when this package drops 0.3 support

**Comment by tkelman** [comment]
> drop support Julia 0.3

Also this would mean you'd need to change the minor version of the package, so be ZMQ.jl v0.4.0.

**Comment by wookay** [comment]
changed like this

ZMQ.jl v0.3.4
- REQUIRE: BinDeps 0.3.22

ZMQ.jl v0.4.0
- REQUIRE: BinDeps 0.3.22

**Comment by wookay** [comment]
changed again.

* ZMQ.jl v0.3.4
 - REQUIRE: BinDeps 0.3.21

*ZMQ.jl v0.4.0
 - REQUIRE: BinDeps 0.3.22

**Comment by tkelman** [comment]
yes, we should do at least one of these now
