### ISSUE TITLE
ZMQ build errors

### ISSUE THREAD

**Issue by geranim0** [JuliaLang/ZMQ.jl#116]
Fresh julia, tried multiple times to purge and not working.

`../libtool: eval: line 6461: unexpected EOF while looking for matching ''
../libtool: eval: line 6462: syntax error: unexpected end of file
Makefile:564: recipe for target 'libzmq.la' failed
make[2]: *** [libzmq.la] Error 2
make[2]: Leaving directory '/home/sam/.julia/v0.4/ZMQ/deps/builds/zmq/src'
Makefile:480: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sam/.julia/v0.4/ZMQ/deps/builds/zmq/src'
Makefile:352: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
=================================[ ERROR: ZMQ ]=================================

LoadError: failed process: Process(setenv(`make -j8`,Union{ASCIIString,UTF8String}["PATH=/home/sam/.julia/v0.4/ZMQ/deps/usr/bin:/home/sam/anaconda3/bin:/home/sam/bin:/home/sam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin","DEFAULTS_PATH=/usr/share/gconf/mate.default.path","QT_ACCESSIBILITY=1","DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-BMOivbpSLE,guid=4a240dc176360cd0adfc860957db4ebc","XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0","MATE_DESKTOP_SESSION_ID=this-is-deprecated","XDG_SESSION_DESKTOP=mate","GTK_OVERLAY_SCROLLING=0","SSH_AGENT_PID=2194","XDG_SESSION_TYPE=x11","USER=sam","XDG_CONFIG_DIRS=/etc/xdg/xdg-mate:/etc/xdg","QT_IM_MODULE=ibus","LESSCLOSE=/usr/bin/lesspipe %s %s","QT_STYLE_OVERRIDE=gtk","CLUTTER_BACKEND=x11","GDMSESSION=mate","CLUTTER_IM_MODULE=xim","XDG_DATA_DIRS=/usr/share/mate:/usr/share/mate:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop","LESSOPEN=| /usr/bin/lesspipe %s","SHELL=/bin/bash","XDG_SEAT=seat0","XAUTHORITY=/home/sam/.Xauthority","GTK_MODULES=gail:atk-bridge:canberra-gtk-module:topmenu-gtk-module","GTK_IM_MODULE=ibus","SESSION_MANAGER=local/samubuntu:@/tmp/.ICE-unix/2125,unix/samubuntu:/tmp/.ICE-unix/2125","QT_QPA_PLATFORMTHEME=appmenu-qt5","XMODIFIERS=@im=ibus","TERM=xterm","HOME=/home/sam","COLORTERM=mate-terminal","GTK2_MODULES=overlay-scrollbar","COMPIZ_CONFIG_PROFILE=mate","XDG_CURRENT_DESKTOP=MATE","LANG=en_CA.UTF-8","SHLVL=1","LOGNAME=sam","XDG_RUNTIME_DIR=/run/user/1000","SSH_AUTH_SOCK=/run/user/1000/keyring/ssh","DESKTOP_SESSION=mate","GDM_LANG=en_CA","OLDPWD=/home/sam","_=bin/julia","PWD=/home/sam/julia-2e358ce975","DISPLAY=:0.0","LANGUAGE=en_CA:en","XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/sam","XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1","XDG_VTNR=7","WINDOWID=48234525","MANDATORY_PATH=/usr/share/gconf/mate.mandatory.path","XDG_SESSION_ID=c4","PKG_CONFIG_PATH=/home/sam/.julia/v0.4/ZMQ/deps/usr/lib/pkgconfig","QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1","QT4_IM_MODULE=xim","LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","OPENBLAS_MAIN_FREE=1"]), ProcessExited(2)) [2]
while loading /home/sam/.julia/v0.4/ZMQ/deps/build.jl, in expression starting on line 23`

`WARNING: ZMQ had build errors.

 - packages with build errors remain installed in /home/sam/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script
`

**Comment by tkelman** [comment]
Is it repeatable if you do
```jl
rm(Pkg.dir("ZMQ","deps","builds"), recursive=true)
rm(Pkg.dir("ZMQ","deps","downloads"), recursive=true)
rm(Pkg.dir("ZMQ","deps","src"), recursive=true)
rm(Pkg.dir("ZMQ","deps","usr"), recursive=true)
rm(Pkg.dir("ZMQ","deps","deps.jl"))
Pkg.build("ZMQ")
```
?

**Comment by geranim0** [comment]
When I run your commands I get these errors

julia> rm(Pkg.dir("ZMQ","deps","usr"), recursive=true)
ERROR: unlink: no such file or directory (ENOENT)
 in unlink at fs.jl:102
 in rm at file.jl:59

julia> rm(Pkg.dir("ZMQ","deps","deps.jl"))
ERROR: unlink: no such file or directory (ENOENT)
 in unlink at fs.jl:102
 in rm at file.jl:59


and then Pkg.build("ZMQ") fails

**Comment by tkelman** [comment]
Fails in the exact same way? What kind of Linux distribution is this? Julia `versioninfo()` ? Always include this kind of information when you report issues.

**Comment by geranim0** [comment]
Yes it fails the same way.

Ubuntu 16.04, mate DE

Julia version:

julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by tkelman** [comment]
Apparently I have seen this before (though I didn't remember, google remembered for me - https://groups.google.com/forum/#!topic/julia-dev/WnhN9zco_08). Not sure what the solution was there. Maybe gist the file at `/home/sam/.julia/v0.4/ZMQ/deps/builds/zmq/libtool` or if you can find another `libtool` script somewhere else in that build tree?

**Comment by geranim0** [comment]
gist: [https://gist.github.com/geranim0/e38b8f9737b5f076db778eec0d68fb93](url)

**Comment by tkelman** [comment]
That doesn't make much sense to me, the lines around 6461-6462 are
```
void lt_debugprintf (const char *file, int line, const char *fmt, ...);
void lt_fatal (const char *file, int line, const char *message, ...);
static const char *nonnull (const char *s);
static const char *nonempty (const char *s);
void lt_setenv (const char *name, const char *value);
char *lt_extend_str (const char *orig_value, const char *add, int to_end);
```
which is in some C code that it's probably using to test for or dynamically load shared libraries, something like that.

Are the line numbers in the error message always consistent?

Since you're using ubuntu, maybe you could try installing libzmq from `apt-get` ? I'm not sure exactly what the package name should be, there currently isn't an apt-get BinDeps provider set up in `deps/build.jl`.

**Comment by tkelman** [comment]
Could you record and gist the entire output? The real error message is probably much higher up in the output.

**Comment by geranim0** [comment]
Installing libzmq3-dev did the trick.

Thanks !

**Comment by tkelman** [comment]
There's some real bug here but it is a pain to debug autotools issues.
