### ISSUE TITLE
Is only 3.2.4 used? Looked to me, looking at the code; should I be worried?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/ZMQ.jl#119]
README says 3 or later, may not be contradicting..

Unclear if 4 is also supported; maybe you can hack any minor or major version to work..

I also notice a higher level:

https://github.com/zeromq/czmq

Was it considered when wrapping? I'm still getting my head around zmq, not really sure if legacy 3 is a problem.. or if higher level would help (smaller API? easier to wrap? is 4 difficult to wrap or just not done yet?)

**Comment by yuyichao** [comment]
> Is only 3.2.4 used?

No

> should I be worried?

No
