### ISSUE TITLE
Use WinRPM for installing ZMQ.jl

### ISSUE THREAD

**Issue by djpeaco** [JuliaLang/ZMQ.jl#65]
Downloading a binary using WinRPM.jl, rather than compiling from source, would simplify the dependencies when installing ZMQ.jl.  @tkelman has more info on this issue.

**Comment by tkelman** [comment]
Thanks. Care to try `Pkg.update(); Pkg.checkout("ZMQ", "tk/winrpm")` and let me know how that looks?

**Comment by djpeaco** [comment]
Looks good. Using the following, I was able to get cleanup my broken packages and get IJulia installed from behind our proxy:

    Pkg.update()
    Pkg.rm("IJulia")
    Pkg.add("ZMQ")
    Pkg.checkout("ZMQ", "tk/winrpm")
    Pkg.add("IJulia")

Does that adequately test that ZMQ was properly installed?

**Comment by tkelman** [comment]
That is great news, thanks for testing that @djpeaco. If you could also try running `Pkg.test("ZMQ")`, and `using IJulia; notebook()` and verify that everything looks functional then I'll open a proper PR from that branch and ping anyone who's contributed to this repo for feedback.

**Comment by djpeaco** [comment]
Yep, that all works. Thanks!
