### ISSUE TITLE
using ZMQ generates error

### ISSUE THREAD

**Issue by sononix** [JuliaLang/ZMQ.jl#67]
using ZMQ
WARNING: zero{T}(::Type{Ptr{T}}) is deprecated, use Ptr{T}(0) instead.
 in depwarn at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in zero at deprecated.jl:29
 in anonymous at no file
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in reload_path at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib

--------

versioninfo()
Julia Version 0.4.0-dev+2849
Commit 3743969* (2015-01-21 22:50 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

any ideas - cant seem to get a working installation

**Comment by jakebolewski** [comment]
@sononix this is not guaranteed to work on 0.4.  Have you tried 0.3?

**Comment by sononix** [comment]
I had a working installation on 3 but was trying to upgraded to 0.4 ----
the ZMQ package wont work on 4 then :)

**Comment by jiahao** [comment]
julia 0.4 is not ready to be used by end users.

**Comment by sononix** [comment]
After 2 days Im beginning to see that - tks M

**Comment by amitmurthy** [comment]
Try doing a `Pkg.checkout("ZMQ")` - it should help with 0.4

**Comment by sononix** [comment]
does see to improve much 

Pkg.checkout("ZMQ")
ERROR: ZMQ is not a git repo
 in checkout at pkg/entry.jl:194
 in anonymous at pkg/dir.jl:28
 in cd at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in cd at pkg/dir.jl:28
 in checkout at pkg.jl:34

I'll just head back to 0.3 -

**Comment by amitmurthy** [comment]
I think you have removed ZMQ . `Pkg.checkout("ZMQ")` should work after it has been installed using `Pkg.add`. Also, the error printed is just a warning, ZMQ should work just fine - just ignore the warnings.

**Comment by amitmurthy** [comment]
I meant the warnings printed as part of `using ZMQ`. But, yes, if have no need of 0.4 specific features, 0.3 is the correct release to use.
