### ISSUE TITLE
latest ccall changes break ZMQ.jl

### ISSUE THREAD

**Issue by skariel** [JuliaLang/ZMQ.jl#71]
see discussion here:

https://groups.google.com/forum/?fromgroups=#!topic/julia-users/vPbhQmQR1pE
https://groups.google.com/forum/?fromgroups=#!topic/julia-users/qi6HpMrAS_A

**Comment by jiahao** [comment]
Confirming that rolling back `julia` to 59eb72a (the last commit before JuliaLang/julia#9986) fixes the problem with IJulia for me.

**Comment by skariel** [comment]
I've managed to fix with the following changes to ZMQ.jl:

change line 403 from:
```julia
    Message(m::ByteString) = Message(m, convert(Ptr{Uint8}, pointer(m.data)), sizeof(m))
```
to:
```julia
    Message(m::ByteString) = Message(m, Base.unsafe_convert(Ptr{Uint8}, pointer(m.data)), sizeof(m))
```
change line 500 from
```julia
    rc = ccall((:zmq_msg_send, zmq), Cint, (Ptr{Void}, Ptr{Message}, Cint),
                &zmsg, socket.data, flag)
```
to:
```julia

    rc = ccall((:zmq_msg_send, zmq), Cint, (Ref{Message}, Ptr{Message}, Cint),
                zmsg, socket.data, flag)
```

of course this has to be done in a backwards compatible way and all, but meanwhile works with me :)
