### ISSUE TITLE
Julia ZMQ Performance Benchmark (performance quite poor)

### ISSUE THREAD

**Issue by daiwei89** [JuliaLang/ZMQ.jl#77]
Hi,
    I've done some latency and throughput test with Julia ZMQ on two nodes linked by 10Gbits ethernet. Both the latency and throughput are an order magnitude slower than the ZeroMQ's test program.

Two tests I'm comparing:
1) ZeroMQ's test program: http://zeromq.org/results:perf-howto
2) My Julia code using ZMQ.jl is here: https://github.com/daiwei89/julia-test

Latency with ZeroMQ's test program: 67~77 micro sec (Message size 16 bytes)
Latency with Julia ZMQ: 400~500 micro sec. (Message size is <10 bytes)

Throughput with ZeroMQ's test program: 201MB/s (Message size 16K bytes)
Throughput with Julia ZMQ: 17~19MB/s (Message size 16K bytes)

Each test sends 1000 messages and take the average time/throughput.

I believe I've avoid all the copying but this is still quite a dismal performance. Is there way to optimize? How does this stack up against Julia's internal RPC calls? 

I'm thinking about building distributed solver with Julia for machine learning, such as gradient descent. Would appreciate any pointer on how to go about it.

Thank you!

**Comment by ihnorton** [comment]
> Is there way to optimize?

Putting your hot code inside of a function usually gives a dramatic improvement (the compiler is very conservative with global variables right now). See http://docs.julialang.org/en/release-0.3/manual/performance-tips/

> How does this stack up against Julia's internal RPC calls?

Not sure if anyone has done that benchmark. cc @amitmurthy who is working on MPI and other transports.

**Comment by afekz** [comment]
@daiwei89  if you code did need function inclusion as per @ihnorton 's comment, did you get a chance to rerun and re-evaluate performance? If so, what were the results?

**Comment by jasonmorton** [comment]
I tried wrapping the client and server loops in https://github.com/daiwei89/julia-test in a function and running multiple times so it would compile.  The results were similar, over 300 micro sec
Latency: 0.000546033279s
Latency: 0.000375234327s
Latency: 0.000324061256s
This is using localhost.  By comparision ZMQ test local_lat and remote_lat gave 38 microseconds.

**Comment by daiwei89** [comment]
Thanks for doing the test. Sorry I haven't had time lately.

On Fri, May 15, 2015 at 2:05 PM, Jason Morton <notifications@github.com>
wrote:

> I tried wrapping the client and server loops in
> https://github.com/daiwei89/julia-test in a function and running multiple
> times so it would compile. The results were similar, over 300 micro sec
> Latency: 0.000546033279s
> Latency: 0.000375234327s
> Latency: 0.000324061256s
> This is using localhost. By comparision ZMQ test local_lat and remote_lat
> gave 38 microseconds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/ZMQ.jl/issues/77#issuecomment-102473828>.
>



-- 
Dai Wei
Ph.D. Candidate
Machine Learning, School of Computer Science
Carnegie Mellon University
http://daiwei89.github.io/

**Comment by timholy** [comment]
In https://github.com/daiwei89/julia-test/pull/1, I got the following results:
```sh
Client entering latency test
Latency: 0.000498601996s
Client entering throughput test
Throughput: 2.6380852415353093e7 bytes/s (1000 msgs, time: 0.621056505)
```
From the 0MQ benchmarks, I got:
```
./remote_lat tcp://127.0.0.1:5555 1 100000
message size: 1 [B]
roundtrip count: 100000
average latency: 43.392 [us]
```
and
```
./local_thr tcp://*:5555 1 100000
message size: 1 [B]
message count: 100000
mean throughput: 3771023 [msg/s]
mean throughput: 30.168 [Mb/s]
```
Performance is very competitive. I think this issue can be safely closed.

**Comment by daiwei89** [comment]
Thanks for the modification. Just accepted the pull request.

On Sat, Aug 1, 2015 at 5:30 AM Tim Holy <notifications@github.com> wrote:

> In daiwei89/julia-test#1 <https://github.com/daiwei89/julia-test/pull/1>,
> I got the following results:
>
> Client entering latency test
> Latency: 0.000498601996s
> Client entering throughput test
> Throughput: 2.6380852415353093e7 bytes/s (1000 msgs, time: 0.621056505)
>
> From the 0MQ benchmarks, I got:
>
> ./remote_lat tcp://127.0.0.1:5555 1 100000
> message size: 1 [B]
> roundtrip count: 100000
> average latency: 43.392 [us]
>
> and
>
> ./local_thr tcp://*:5555 1 100000
> message size: 1 [B]
> message count: 100000
> mean throughput: 3771023 [msg/s]
> mean throughput: 30.168 [Mb/s]
>
> Performance is very competitive. I think this issue can be safely closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/ZMQ.jl/issues/77#issuecomment-126909143>.
>
-- 
David Dai
