### ISSUE TITLE
No build error, but build failure: absence of GLIBCXX_3.4.20 in Julia libstdc++.so.6?

### ISSUE THREAD

**Issue by jasonmorton** [JuliaLang/ZMQ.jl#81]
I'm getting a build failure (Ubuntu 15.04), although there are no errors displayed in the build process.  It will build if libzmq is installed (version 2) but not with libzmq3 or with the packaged binary dependencies.

I've possibly narrowed the problem down to the following.  I tried copying the deps.jl from another machine where the build was successful (ZMQ.version is v"3.2.4"), which fails when loading is attempted. Trying to load ZMQ directly gives the error:

Base.dlopen("/home/morton/.julia/v0.3/ZMQ/deps/usr/lib/libzmq.so")
ERROR: could not load module /home/morton/.julia/v0.3/ZMQ/deps/usr/lib/libzmq.so: /home/morton/julia-79599ada44/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/morton/.julia/v0.3/ZMQ/deps/usr/lib/libzmq.so)
 in dlopen at c.jl:19

Now checking for that dependency,
strings ~/julia-79599ada44/lib/julia/libstdc++.so.6| grep GLIBC 
shows that GLIBCXX_3.4.19 is the highest offered.

**Comment by tkelman** [comment]
Are you using the generic linux binaries of Julia? What is the system gcc version for Ubuntu 15.04? You might need to use the PPA or a source-compiled version of Julia to work with a bleeding-edge OS version, until we have a chance to rebuild the GCC version we use on the buildbots.

**Comment by jasonmorton** [comment]
I am using the generic linux binaries.  The system gcc is 4.9.2, which should include 3.4.20.  I don't know how to get the ZMQ build to look at the system libstdc++.so.6, which would probably solve this.

The ppa doesn't have a 15.04 build yet, and the existing builds won't install.  I will try compiling from source, but expect some issues.  Know of any workaround?

**Comment by tkelman** [comment]
Try renaming `julia-79599ada44/lib/julia/libstdc++.so.6` out of the way

**Comment by jasonmorton** [comment]
bingo, renaming julia-79599ada44/lib/julia/libstdc++.so.6 out of the way did it.  All tests passed with 3.2.4.  Many thanks.

**Comment by tkelman** [comment]
deja vu all over again, damn fortran and c++ constantly breaking abi...
