### ISSUE TITLE
Blocking in nonblocking mode

### ISSUE THREAD

**Issue by jasonmorton** [JuliaLang/ZMQ.jl#82]
The implementation of send and recv sets the DONTWAIT/NOBLOCK flag to nonblocking in the ccall 
[v2] (https://github.com/JuliaLang/ZMQ.jl/blob/master/src/ZMQ.jl#L563) [v3] (https://github.com/JuliaLang/ZMQ.jl/blob/master/src/ZMQ.jl#L584).  Some language bindings let this be set by the user, so one would expect that the Julia recv is always nonblocking.

But, when, for example, connecting to a socket that was not bound, or on which there are no messages, the errno which is returned equals EAGAIN (on my machine, 11).  Thus the [inner loop] (https://github.com/JuliaLang/ZMQ.jl/blob/master/src/ZMQ.jl#L587)
is entered, and the send or recv blocks indefinitely.  [Example] (https://gist.github.com/jasonmorton/d914bd93b34e8fc66b73)

I encountered this when trying to translate the python example [msreader] (https://github.com/imatix/zguide/blob/master/examples/Python/msreader.py#L31) into Julia.  We can't do this trick because the recv may not return if there is nothing on the other side of the connection, or even when there is a connection but there is no message and EAGAIN is triggered.  As a result the msreader example does not seem to be possible (without handling the hanging recv with a Task or something).

**Comment by stevengj** [comment]
I think the reason that we set it to `NOBLOCK` is that we wanted it to act like other I/O in Julia: if you are reading from any I/O device, the Julia scheduler allows other asynchronous tasks (green threads) to run while it is waiting.

If you want to do asynchronous I/O with zeromq, it seems more Julian to use a `Task` like you would for any other asynchronous I/O in Julia.  Is that a problem here?

**Comment by vtjnash** [comment]
that example code looks like a terrible design to me. why is it doing a busy polling loop at 1ms intervals?

Julia exposes non-blocking IO through Tasks: each of those `while true` loops in that example can be rewritten to each be handled by their own task, no expensive busy loop polling required.

**Comment by StefanKarpinski** [comment]
Right, we don't do the whole blocking vs. non-blocking parallel I/O APIs thing: all Julia I/O is semantically blocking and concurrent tasks are used to do many things at once with the multiplexing handled automatically by the task scheduler.

**Comment by jasonmorton** [comment]
The python example is not supposed to be good code -- it is just an example in the book, after which they show you a better way to do it.  I was going to try to work through translating all the zguide examples to Julia and this was the first example that didn't seem to be translatable, because the binding didn't expose the full API.  I think it is fine -- zeromq seems to encourage opinionated bindings.

**Comment by StefanKarpinski** [comment]
Making it impossible to express the bad way to do something? Winning.
