### ISSUE TITLE
support precompiling

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/ZMQ.jl#85]
Currently, the ZMQ module does not properly support the new precompiling feature in Julia 0.4, because it relies on detecting the libzmq version at runtime, so I've marked it with `__precompile__(false)` for now.

Possible solutions:
* Settle on the libzmq version at `Pkg.build` time and put it in `deps.jl` or similar.
* Drop support for older libzmq versions (just throw an error in `__init__` if one is found)
* Move all of the version-dependent stuff into `__init__`.

**Comment by StefanKarpinski** [comment]
> Move all of the version-dependent stuff into `__init__`.

This sounds superficially like the easiest option – what are the issues with it?

**Comment by stevengj** [comment]
@StefanKarpinski it is ugly and slow to `@eval` a whole bunch of functions in `__init__`.

**Comment by Keno** [comment]
I vote for
```
Settle on the libzmq version at Pkg.build time and put it in deps.jl or similar.
```
This is no different than moving libraries around in which case you have to rebuild as well.

**Comment by stevengj** [comment]
Considering that libzmq v2 was last updated in 2012, v3 was released in 2011, and the current version is v4, it doesn't make sense to me to support v2 any more.
