### ISSUE TITLE
"uv_hook_pollcb not defined" error in some 0.4-dev versions

### ISSUE THREAD

**Issue by jbn** [JuliaLang/ZMQ.jl#89]
I'm using Julia v"0.4.0-dev+6140" and the latest ZMQ.jl. This morning, IJulia using the 0.4 kernel would not start. It kept dying, then restarting, then dying, ad infinitum. I don't know enough about ZMQ or IPython to offer a patch. But, I can tell you my error message, and how I fixed it. Hopefully someone can use that information to grok the problem. 

Error in IJulia (given verbose and no capture on the stderr):

    ERROR: LoadError: UndefVarError: _uv_hook_pollcb not defined

    in send at /Users/generativist/.julia/v0.4/ZMQ/src/ZMQ.jl:563

To fix, I replaced line 310, with:

    notify(socket::Socket) = Base.uv_pollcb(socket.pollfd.handle, Int32(0), Int32(Base.UV_READABLE))

**Comment by stevengj** [comment]
@vtjnash, you added the `_uv_hook_pollcb` call in #86, can you comment?

**Comment by stevengj** [comment]
@jbn, maybe you just need a newer 0.4 build?

**Comment by stevengj** [comment]
In particular, it looks like `_uv_hook_pollcb` was removed in JuliaLang/julia@176ca4f8e1de4998023818ab43dc038e4e535c3a but `_FDWatcher` was added in https://github.com/JuliaLang/julia@94de95e8fe73151f5b83882fc42356bc269bb79f, and any 0.4-dev release in between these two commits isn't going to work.

I'm not sure if it's worth trying to support every 0.4 commit; I suspect we should just tell people to upgrade their 0.4-dev if they run into this.

**Comment by jbn** [comment]
Nice sleuthing, @stevengj. 

Just built the nightly. I'm back in safe, unpatched territory.

**Comment by tkelman** [comment]
I'm going to close this as a wontfix then, unless someone wants to submit a PR for making things work for that particular range of not-latest 0.4.0-dev versions.
