### ISSUE TITLE
ZMQ not pulling latest version for Ubuntu?

### ISSUE THREAD

**Issue by CorySimon** [JuliaLang/ZMQ.jl#97]
Pkg.status()
gives

    - ZMQ                           0.3.0+             master
    - IJulia                        1.1.8              master
i.e. I have the latest version of ZMQ. But when I type using IJulia,

```
 ERROR: LoadError: InitError: ZMQ version 2.2.0 < 3 is not supported
 in error at ./error.jl:21
 in __init__ at /home/cory/.julia/v0.4/ZMQ/src/ZMQ.jl:563
 in _require_from_serialized at loading.jl:84
 in require at ./loading.jl:225
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:284
 in _start at ./client.jl:411
during initialization of module ZMQ
while loading /home/cory/.julia/v0.4/IJulia/src/IJulia.jl, in expression starting on line 15
ERROR: Failed to precompile IJulia to /home/cory/.julia/lib/v0.4/IJulia.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:383
 in require at ./loading.jl:250
```

Someone from IJulia said to report this to you [https://github.com/JuliaLang/IJulia.jl/issues/384](https://github.com/JuliaLang/IJulia.jl/issues/384).

**Comment by tkelman** [comment]
Linux, presumably? What distribution?

**Comment by CorySimon** [comment]
Yes, I am using Ubuntu 14.04. Update: I installed a later version of ZMQ using apt-get, and now the IJulia notebook works. http://zeromq.org/distro:debian

    apt-get install libzmq3-dev

**Comment by trappmartin** [comment]
I had the same issue, installing the dev package helped as well.

**Comment by naipmoro** [comment]
I'm on ubuntu 12.04 and libzmq3-dev doesn't exist. I tried installing libzmq-dev, but that made no difference. Still getting 'ERROR: LoadError: LoadError: InitError: ZMQ version 2.1.11 < 3 is not supported'

**Comment by stevengj** [comment]
I think you need at least Ubuntu 14.04 (trusty) for libzmq3?

**Comment by JeffBezanson** [comment]
+1

Does something need to be done in BinDeps to support this? If Pkg.build succeeds, you should not then get a run time error saying you have the wrong version of the library.

**Comment by tkelman** [comment]
I believe we could move the version check from `__init__` https://github.com/JuliaLang/ZMQ.jl/blob/d82e842017df5c0193adf1fd8733e92e0cb21f74/src/ZMQ.jl#L571-L581 to a BinDeps verify hook, a la https://github.com/JuliaOpt/Cbc.jl/blob/master/deps/build.jl

**Comment by simonbyrne** [comment]
Hopefully should be working now with a combination of #121 and #118
